---
openapi: 3.0.2
info:
  title: Planet 4 v0.1
  version: 1.0.0
  description: Planet 4 API for events, supporters, etc.
paths:
  /events:
    get:
      parameters:
      - name: startdate
        description: start event date
        schema:
          type: string
        in: query
      - name: enddate
        description: end event date
        schema:
          type: string
        in: query
      responses:
        200:
          description: all events
      summary: all events
  /events/category/{categoryid}:
    get:
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          description: Events by category
    parameters:
    - name: categoryid
      description: Category id
      schema:
        type: string
      in: path
      required: true
  /events/location/{locationid}: {}
  /events/supporter/{supporterid}:
    get:
      parameters:
      - name: supporterid
        description: Supporter ident
        schema:
          type: string
        in: path
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          description: All events by supported
components:
  schemas:
    Event:
      description: Planet 4 event, eventually created from different sources (OS,
        CS)
      required:
      - id
      type: object
      properties:
        description:
          description: Text describing the event. From Open Social attributes->body->value
          type: string
        id:
          description: Unique Id self-generated? in control shift this slug
          type: string
        title:
          description: Title of the Event
          type: string
        categories:
          description: Categories the events falls into
          type: array
          items:
            type: string
        location:
          description: Lat,Long,...
          type: string
        startDate:
          description: Start event day
          type: string
        endDate:
          description: End event date
          type: string
        summary:
          description: Short description about the event
          type: string
        url:
          description: Link to the URL content
          type: string
    Supporter:
      description: Person potentially supporting one or more Events
      required:
      - id
      - firstName
      - lastName
      - email
      type: object
      properties:
        id:
          description: ""
          type: string
        firstName:
          description: ""
          type: string
        lastName:
          description: ""
          type: string
        email:
          description: ""
          type: string
    Enrollment:
      description: Ties one Supporter with one Event
      required:
      - endDate
      - supporterId
      - eventId
      type: object
      properties:
        endDate:
          format: date-time
          description: ""
          type: string
        supporterId:
          description: ""
          type: string
        eventId:
          description: Event Ident
          type: string
